apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: party-pic-server

namespace: party-pic

resources:
  - deployment.yaml
  - service.yaml
  - secrets.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: party-pic-server
  app.kubernetes.io/part-of: party-pic
