apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: party-pic-server-pdb
  labels:
    app: party-pic-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: party-pic-server
