apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: party-pic-server-monitor
  labels:
    app: party-pic-server
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: party-pic-server
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s