apiVersion: v1
kind: Service
metadata:
  name: party-pic-server
  labels:
    app: party-pic-server
spec:
  type: ClusterIP
  selector:
    app: {{ include "party-pic-server.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
