apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/BenediktNau/PartyPic.git
    targetRevision: simon
    path: party-pic_server/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: party-pic

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
