apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: party-pic-client-pdb
  labels:
    app: party-pic-client
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: party-pic-client
