apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: party-pic-client

namespace: party-pic

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: party-pic-client
  app.kubernetes.io/part-of: party-pic
