apiVersion: v1
kind: Service
metadata:
  name: party-pic-client
  labels:
    app: party-pic-client
spec:
  type: ClusterIP
  selector:
    app: party-pic-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
