apiVersion: v1
kind: Secret
metadata:
  name: party-pic-secrets
type: Opaque
stringData:
  # Datenbank
  db-host: "your-db-host"          # TODO: Ersetze mit echtem Host
  db-port: "5432"
  db-name: "partydb"
  db-user: "partyuser"
  db-password: "your-db-password"  # TODO: Ersetze mit echtem Passwort
  
  # S3/Object Storage
  s3-endpoint: "http://localhost:9000"  # TODO: Ersetze mit echtem Endpoint
  s3-access-key: "minioadmin"         # TODO: Ersetze mit echtem Key
  s3-secret-key: "minioadmin"         # TODO: Ersetze mit echtem Key
  s3-bucket-name: "dev-foto-bucket"       # TODO: Ersetze mit echtem Bucket
  s3-region: "us-east-1"
  
  # JWT
  jwt-secret: "StRoNGs3crE7" # TODO: Ersetze mit sicherem Secret
