# =============================================================================
# PARTY-PIC CLIENT HELM CHART
#
# Helm Chart fuer das React Frontend.
# Deployed Deployment, Service, Ingress, HPA und PDB.
# =============================================================================
apiVersion: v2
name: party-pic-client
description: A Helm chart for the party pic client
type: application
version: 0.1.0
appVersion: "1.0.0"