name: Build Client

on:
  push:
    branches:
      - "master"
      - "elias"
    paths:
      - 'party-pic_client/**'       # Watch everything in the server folder...
      - '!party-pic_client/chart/**'  # ...BUT ignore the k8s subfolder

env:
  REGISTRY: ghcr.io
  # Naming the image specifically for the server
  IMAGE_NAME: ${{ github.repository }}-client 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # Point context to the server subfolder
          context: ./party-pic_client
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Kubernetes Manifest
        env:
          FULL_IMAGE_NAME: ${{ steps.meta.outputs.tags }}
        run: |
          # Install yq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

          # 1. Extract just the tag (everything after the colon)
          # Input: ghcr.io/user/repo:sha-12345 -> Output: sha-12345
          NEW_TAG=$(echo $FULL_IMAGE_NAME | cut -d':' -f2)
          
          
          # 2. Go to the chart folder
          cd party-pic_client/chart

          # 3. Update the 'tag' field in values.yaml
          yq -i ".image.tag = \"$NEW_TAG\"" values.yaml
          
      - name: Commit and Push Manifest Change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Only add the specific file we changed
          git add party-pic_client/chart/values.yaml
          git commit -m "Update client image to ${{ steps.meta.outputs.tags }}"
          git push
